spring:
  web:
    resources:
      static-locations: classpath:/dist/

server:
  port: 5028

Mta:
  secret-key: SXJYDeepReads123

file:
  site_info: "src/main/resources/txt/site_info.txt"
  mitochondrial_detail: "src/main/resources/txt/mitochondrial_detail.txt"
  outcome: "src/main/resources/txt/outcome.txt"
  records: "src/main/resources/txt/records.txt"